apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      volumes:
        - name: app-volume
          emptyDir: {}

      containers:
        - name: fastapi
          image: python:3.11-slim
          command: ["sh", "-c"]
          args:
            - |
              apt-get update
              apt-get install nano bash git
              git clone https://github.com/cheongfish/Study-Database.git
              cd Demo/Sharding/app
              pip install --no-cache-dir -r ./requirements.txt
              # sleep infinity
              uvicorn app:app --host 0.0.0.0 --port 8081
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: app-volume
              mountPath: /app
